# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'group_zone.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
import os

class group_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(519, 387)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(380, 340, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)

        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 55, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        #number of the rack 
        self.textEdit0 = QtWidgets.QTextEdit(Form)
        self.textEdit0.setGeometry(QtCore.QRect(190, 105, 231, 21))
        self.textEdit0.setObjectName("textEdit0")

        #ZGName
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(190, 135, 231, 21))
        self.textEdit.setObjectName("textEdit")
        #SAS_ConnectA
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(190, 165, 231, 21))
        self.textEdit_2.setObjectName("textEdit_2")

        #SAS ConnectB
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(190, 195,231, 21))
        self.textEdit_3.setObjectName("textEdit_3")

        #SX890_7
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(190, 225, 231, 21))
        self.textEdit_4.setObjectName("textEdit_4")

        #SX890_15
        self.textEdit_5 = QtWidgets.QTextEdit(Form)
        self.textEdit_5.setGeometry(QtCore.QRect(190, 255, 231, 21))
        self.textEdit_5.setObjectName("textEdit_5")



        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 90, 141, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        #number of rack 
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)

        #ZGName
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        #SASConnectA
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        #SASConnectB
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        #SX890_7
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        #SX890_15
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)

        self.pushButton.clicked.connect(self.button_clicked)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Group Zone"))
        self.pushButton.setText(_translate("Form", "Create"))

        self.label.setText(_translate("Form", "Create a Zone group"))
        self.label_2.setText(_translate("Form", "ZGNAme"))
        self.label_4.setText(_translate("Form", "SASConnectA"))
        self.label_5.setText(_translate("Form", "SASConnectB"))
        self.label_6.setText(_translate("Form", "SX890_7"))
        self.label_7.setText(_translate("Form", "SX890_15"))
        self.label_8.setText(_translate("Form", "rack number"))

    def button_clicked(self):
        print("created")
        #Translate them into text 
        rackNumber = self.textEdit0.toPlainText()

        ZGName = self.textEdit.toPlainText() 
        SASConnectA = self.textEdit_2.toPlainText() 
        SASConnectB = self.textEdit_3.toPlainText()
        SX890_7 = self.textEdit_4.toPlainText()
        SX890_15 = self.textEdit_5.toPlainText()

        group_zone_file = "GroupZones_{a}.json".format(a = rackNumber)
        #make a counter 
        if os.path.exists(group_zone_file):
            with open(group_zone_file, 'r+') as f:
                data = json.load(f)
                #print(data)
        else:
            data = {"counter": 0}

        exp = {"SASConnectA": SASConnectA,
        "SASConnectB": SASConnectB,
        "SX890_7": SX890_7,
        "SX890_15" : SX890_15}
        
        my_json = {"ZGName": ZGName, "Exphy" : {}}
        for k, v in exp.items():
            if exp[k] != "":
                my_json["Exphy"][k] = v 

        data[data["counter"]] = my_json
        data["counter"]+=1
        json_object = json.dumps(data, indent=4)
    
        with open(group_zone_file, "w+") as outfile:
            outfile.write(json_object)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = group_Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
