# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menna.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import json
import webbrowser
from PyQt5 import QtCore, QtGui, QtWidgets
from group_zone import group_Ui_Form
from set_zone import set_Ui_Form
from PyQt5.QtCore import QCoreApplication

'''
1. putting it one by one is not easy but will ease the edit
'''
class Ui_MainWindow_a(object):
    def __init__(self) -> None:
        self.zone_list = []

    def group_clicked(self):
        self.window = QtWidgets.QWidget()
        self.ui = group_Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()
        #print('Hi group')

    def set_clicked(self):
        self.setwindow = QtWidgets.QWidget()
        self.sui = set_Ui_Form()
        self.sui.setupUi(self.setwindow)
        self.setwindow.show()
        #print('hi set')   

    def fj_clicked(self):
        #Link of SAS browser in our racks 
        webbrowser.open('http://192.168.4.11')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(35, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)

        self.Close = QtWidgets.QPushButton(self.centralwidget)
        self.Close.setObjectName("Close")
        self.gridLayout_2.addWidget(self.Close, 3, 1, 1, 1)


        self.FinishButton = QtWidgets.QPushButton(self.centralwidget)
        self.FinishButton.setObjectName("finishButton")
        #edit 1 
        self.FinishButton.clicked.connect(self.button_clicked)
        self.Close.clicked.connect(QCoreApplication.instance().quit)


        self.gridLayout_2.addWidget(self.FinishButton, 2, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.layoutWidget = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 341, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        
        
        self.formLayout_9 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout_9.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout_9.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout_9.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout_9.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout_9.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.formLayout_9.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout_9.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout_9.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout_9.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.formLayout_9.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget1.setGeometry(QtCore.QRect(390, 10, 261, 441))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.formLayout_10 = QtWidgets.QFormLayout(self.layoutWidget1)
        self.formLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.FixedColumnWidth)
        self.textEdit.setObjectName("textEdit")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.textEdit)
        self.textEdit_4 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_4.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.textEdit_4)
        self.textEdit_8 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_8.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_8.setObjectName("textEdit_8")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.textEdit_8)
        self.textEdit_6 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_6.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_6.setObjectName("textEdit_6")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.textEdit_6)
        self.textEdit_5 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_5.setMaximumSize(QtCore.QSize(16777215, 21))
        self.textEdit_5.setObjectName("textEdit_5")
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.textEdit_5)
        self.textEdit_7 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_7.setMaximumSize(QtCore.QSize(16777215, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.formLayout_10.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.textEdit_7)
        self.textEdit_3 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_3.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.formLayout_10.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.textEdit_3)
        self.textEdit_9 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_9.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_9.setObjectName("textEdit_9")
        self.formLayout_10.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.textEdit_9)
        self.textEdit_10 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_10.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_10.setObjectName("textEdit_10")
        self.formLayout_10.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.textEdit_10)
        self.textEdit_11 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_11.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_11.setObjectName("textEdit_11")
        self.formLayout_10.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.textEdit_11)
        self.textEdit_12 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_12.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_12.setObjectName("textEdit_12")
        self.formLayout_10.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.textEdit_12)
        self.textEdit_13 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_13.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_13.setObjectName("textEdit_13")
        self.formLayout_10.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.textEdit_13)
        self.textEdit_14 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_14.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_14.setObjectName("textEdit_14")
        self.formLayout_10.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.textEdit_14)
        self.textEdit_15 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_15.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_15.setObjectName("textEdit_15")
        self.formLayout_10.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.textEdit_15)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_2.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_2.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.textEdit_2.setObjectName("textEdit_2")
        

        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textEdit_2)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")

        self.layoutWidget2 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 290, 491))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget2)
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(10, 20, 10, 10)
        self.formLayout_4.setSpacing(20)
        self.formLayout_4.setObjectName("formLayout_4")

        #group pushbutton
        self.group_pushButton = QtWidgets.QPushButton(self.tab_7)
        self.group_pushButton.setGeometry(QtCore.QRect(10, 306, 93, 30))
        self.group_pushButton.setObjectName("group_pushButton")
        self.group_pushButton.clicked.connect(self.group_clicked)
        #set pushbutton
        self.set_pushButton = QtWidgets.QPushButton(self.tab_7)
        self.set_pushButton.setGeometry(QtCore.QRect(150, 306, 93, 30))
        self.set_pushButton.setObjectName("set_pushButton")
        self.set_pushButton.clicked.connect(self.set_clicked)
        #Fuijitsu pushbutton 
        self.fj_pushButton = QtWidgets.QPushButton(self.tab_7)
        self.fj_pushButton.setGeometry(QtCore.QRect(290, 306, 93, 30))
        self.fj_pushButton.setObjectName("fj_pushButton")
        self.fj_pushButton.clicked.connect(self.fj_clicked)



        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_47.setObjectName("label_47")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)

        self.label_170 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_170.setObjectName("label_170")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_170)

        self.layoutWidget3 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget3.setGeometry(QtCore.QRect(360, 28, 265, 250))
        self.layoutWidget3.setObjectName("layoutWidget3")

        self.formLayout_11 = QtWidgets.QFormLayout(self.layoutWidget3)
        self.formLayout_11.setContentsMargins(0, 0, 0, 0)
        self.formLayout_11.setVerticalSpacing(20)
        self.formLayout_11.setObjectName("formLayout_11")
        self.textEdit_16 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_16.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_16.setObjectName("textEdit_16")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textEdit_16)
        self.textEdit_21 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_21.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_21.setObjectName("textEdit_21")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.textEdit_21)
        self.textEdit_20 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_20.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_20.setObjectName("textEdit_20")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.textEdit_20)
        self.textEdit_17 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_17.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_17.setObjectName("textEdit_17")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.textEdit_17)
        self.textEdit_19 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_19.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_19.setObjectName("textEdit_19")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.textEdit_19)

        self.textEdit_18 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_18.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_18.setObjectName("textEdit_18")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.textEdit_18)

        self.textEdit_70 = QtWidgets.QTextEdit(self.layoutWidget3)
        self.textEdit_70.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_70.setObjectName("textEdit_70")
        self.formLayout_11.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.textEdit_70)



        self.tabWidget.addTab(self.tab_7, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 0, 211, 471))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.layoutWidget4)
        self.formLayout_5.setContentsMargins(0, 10, 10, 10)
        self.formLayout_5.setSpacing(20)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_71 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_71.setObjectName("label_71")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_71)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_72.setObjectName("label_72")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_72)
        self.label_73 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_73.setObjectName("label_73")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_73)
        self.label_70 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_70.setObjectName("label_70")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_70)
        self.label_91 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_91.setObjectName("label_91")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_91)
        self.label_92 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_92.setObjectName("label_92")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_92)
        self.label_90 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_90.setObjectName("label_90")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_90)
        self.label_93 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_93.setObjectName("label_93")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_93)
        self.label_89 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_89.setObjectName("label_89")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_89)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_9)
        self.layoutWidget5.setGeometry(QtCore.QRect(220, 10, 258, 371))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textEdit_46 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_46.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_46.setObjectName("textEdit_46")
        self.verticalLayout_5.addWidget(self.textEdit_46)
        self.textEdit_45 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_45.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_45.setObjectName("textEdit_45")
        self.verticalLayout_5.addWidget(self.textEdit_45)
        self.textEdit_48 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_48.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_48.setObjectName("textEdit_48")
        self.verticalLayout_5.addWidget(self.textEdit_48)
        self.textEdit_47 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_47.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_47.setObjectName("textEdit_47")
        self.verticalLayout_5.addWidget(self.textEdit_47)
        self.textEdit_22 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_22.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_22.setObjectName("textEdit_22")
        self.verticalLayout_5.addWidget(self.textEdit_22)
        self.textEdit_49 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_49.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_49.setObjectName("textEdit_49")
        self.verticalLayout_5.addWidget(self.textEdit_49)
        self.textEdit_53 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_53.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_53.setObjectName("textEdit_53")
        self.verticalLayout_5.addWidget(self.textEdit_53)
        self.textEdit_52 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_52.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_52.setObjectName("textEdit_52")
        self.verticalLayout_5.addWidget(self.textEdit_52)
        self.textEdit_51 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_51.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_51.setObjectName("textEdit_51")
        self.verticalLayout_5.addWidget(self.textEdit_51)
        
        self.textEdit_50 = QtWidgets.QTextEdit(self.layoutWidget5)
        self.textEdit_50.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_50.setObjectName("textEdit_50")
        self.verticalLayout_5.addWidget(self.textEdit_50)
        
        self.tabWidget.addTab(self.tab_9, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 0, 245, 321))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget6)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.layoutWidget7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget7.setGeometry(QtCore.QRect(250, 10, 261, 211))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.formLayout_18 = QtWidgets.QFormLayout(self.layoutWidget7)
        self.formLayout_18.setContentsMargins(0, 0, 0, 0)
        self.formLayout_18.setVerticalSpacing(20)
        self.formLayout_18.setObjectName("formLayout_18")
        self.textEdit_54 = QtWidgets.QTextEdit(self.layoutWidget7)
        self.textEdit_54.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_54.setObjectName("textEdit_54")
        self.formLayout_18.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textEdit_54)
        self.textEdit_55 = QtWidgets.QTextEdit(self.layoutWidget7)
        self.textEdit_55.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_55.setObjectName("textEdit_55")
        self.formLayout_18.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.textEdit_55)
        self.textEdit_56 = QtWidgets.QTextEdit(self.layoutWidget7)
        self.textEdit_56.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_56.setObjectName("textEdit_56")
        self.formLayout_18.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.textEdit_56)
        self.textEdit_57 = QtWidgets.QTextEdit(self.layoutWidget7)
        self.textEdit_57.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_57.setObjectName("textEdit_57")
        self.formLayout_18.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.textEdit_57)
        self.textEdit_58 = QtWidgets.QTextEdit(self.layoutWidget7)
        self.textEdit_58.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_58.setObjectName("textEdit_58")
        self.formLayout_18.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.textEdit_58)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget8 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 0, 251, 201))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_2.addWidget(self.label_41)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_2.addWidget(self.label_39)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_2.addWidget(self.label_29)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_2.addWidget(self.label_40)
        self.layoutWidget9 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget9.setGeometry(QtCore.QRect(260, 0, 261, 206))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.formLayout_19 = QtWidgets.QFormLayout(self.layoutWidget9)
        self.formLayout_19.setContentsMargins(0, 15, 0, 0)
        self.formLayout_19.setVerticalSpacing(30)
        self.formLayout_19.setObjectName("formLayout_19")
        self.textEdit_59 = QtWidgets.QTextEdit(self.layoutWidget9)
        self.textEdit_59.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_59.setObjectName("textEdit_59")
        self.formLayout_19.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.textEdit_59)
        self.textEdit_60 = QtWidgets.QTextEdit(self.layoutWidget9)
        self.textEdit_60.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_60.setObjectName("textEdit_60")
        self.formLayout_19.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.textEdit_60)
        self.textEdit_61 = QtWidgets.QTextEdit(self.layoutWidget9)
        self.textEdit_61.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_61.setObjectName("textEdit_61")
        self.formLayout_19.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.textEdit_61)
        self.textEdit_62 = QtWidgets.QTextEdit(self.layoutWidget9)
        self.textEdit_62.setMaximumSize(QtCore.QSize(400, 21))
        self.textEdit_62.setObjectName("textEdit_62")
        self.formLayout_19.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.textEdit_62)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cloud Automation"))
        self.Close.setText(_translate("MainWindow", "Close"))

        self.FinishButton.setText(_translate("MainWindow", "Finish"))
        self.label_9.setText(_translate("MainWindow", "numberOfServers"))
        self.label_10.setText(_translate("MainWindow", "dictionaryOfServerNamesAndMACAddresses"))
        self.label_11.setText(_translate("MainWindow", "numberOfHarddiskArrays"))
        self.label_12.setText(_translate("MainWindow", "numberOfHarddisksInArray"))
        self.label_13.setText(_translate("MainWindow", "IPVersion"))
        self.label_14.setText(_translate("MainWindow", "managementNetworkIPRange"))
        self.label_15.setText(_translate("MainWindow", "physicalDataNetworkIPRange"))
        self.label_16.setText(_translate("MainWindow", "virtualMachineDataNetworkIPRange"))
        self.label_17.setText(_translate("MainWindow", "frontEndServerMACAddress"))
        self.label_18.setText(_translate("MainWindow", "frontEndServerIPAddress"))
        self.label_19.setText(_translate("MainWindow", "frontEndServerName"))
        self.label_20.setText(_translate("MainWindow", "connectionServerName"))
        self.label_21.setText(_translate("MainWindow", "connectionServerIPAddress"))
        self.label_22.setText(_translate("MainWindow", "connectionServerPortNumber"))
        self.label_23.setText(_translate("MainWindow", "storagePoolConfigurationPreferences"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Physical Network"))
        self.label_8.setText(_translate("MainWindow", "numberOfHarddiskArrays"))
        self.label_2.setText(_translate("MainWindow", "numberOfHarddisksInArray"))
        self.label_7.setText(_translate("MainWindow", "numberOfServers"))
        self.label_6.setText(_translate("MainWindow", "serverNames"))
        self.label_47.setText(_translate("MainWindow", "basicKickstartConfigurations"))
        self.label_5.setText(_translate("MainWindow", "hardiskToServerAssociationMatrix"))
        self.label_170.setText(_translate("MainWindow", "activeZoneSet"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Storage"))
        self.label_71.setText(_translate("MainWindow", "fileSystemType"))
        self.label_72.setText(_translate("MainWindow", "isRAID"))
        self.label_73.setText(_translate("MainWindow", "RAIDLevel"))
        self.label_70.setText(_translate("MainWindow", "partitioningSchema"))
        self.label_91.setText(_translate("MainWindow", "OperatingSystemType"))
        self.label_92.setText(_translate("MainWindow", "packages"))
        self.label_90.setText(_translate("MainWindow", "packageManager"))
        self.label_93.setText(_translate("MainWindow", " installedPackages"))
        self.label_89.setText(_translate("MainWindow", "uninstalledPackages"))


        self.group_pushButton.setText(_translate("Form", "Add Group"))
        self.set_pushButton.setText(_translate("Form", "Add Set"))

        self.fj_pushButton.setText(_translate("Form", "Go Fuijtsu"))


        

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Operating System"))
        self.label_25.setText(_translate("MainWindow", "cloudTechnologyApplication"))
        self.label_27.setText(_translate("MainWindow", "neededPackages"))
        self.label_24.setText(_translate("MainWindow", "DataStoreFileSysyem"))
        self.label_26.setText(_translate("MainWindow", "databaseTool"))
        self.label_28.setText(_translate("MainWindow", "databaseAdminCredentials\n"
""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Cloud Technology"))
        self.label_41.setText(_translate("MainWindow", "IPVersion"))
        self.label_39.setText(_translate("MainWindow", "physicalDataNetworkIPRange"))
        self.label_29.setText(_translate("MainWindow", "numberOfVLANs"))
        self.label_40.setText(_translate("MainWindow", "topology"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "System Network"))
    #edit 2 
    def button_clicked(self):
        '''
        next task: put them in a json file not in .txt 
        '''
        print("clicked")
        #Physical network 
        numberOfServers = self.textEdit_2.toPlainText()
        dictionaryOfServerNamesAndMACAddresses = self.textEdit.toPlainText()
        numberOfHarddiskArrays = self.textEdit_4.toPlainText()
        numberOfHarddisksInArray = self.textEdit_8.toPlainText()
        IPVersion = self.textEdit_6.toPlainText()
        managementNetworkIPRange = self.textEdit_5.toPlainText()
        physicalDataNetworkIPRange = self.textEdit_7.toPlainText()
        virtualMachineDataNetworkIPRange = self.textEdit_3.toPlainText()
        frontEndServerMACAddress = self.textEdit_9.toPlainText()
        frontEndServerIPAddress = self.textEdit_10.toPlainText()
        frontEndServerName = self.textEdit_11.toPlainText()
        connectionServerName = self.textEdit_12.toPlainText()
        connectionServerIPAddress = self.textEdit_13.toPlainText()
        connectionServerPortNumber = self.textEdit_14.toPlainText()
        storagePoolConfigurationPreferences = self.textEdit_15.toPlainText()
        
        #SAS
        numberOfHarddiskArrays_SAS = self.textEdit_16.toPlainText()
        numberOfHarddisksInArray_SAS = self.textEdit_21.toPlainText()
        numberOfServers_SAS = self.textEdit_20.toPlainText()
        serverNames_SAS = self.textEdit_17.toPlainText()
        basicKickstartConfigurations = self.textEdit_19.toPlainText()
        hardiskToServerAssociationMatrix = self.textEdit_18.toPlainText()
        activeZoneSet = self.textEdit_70.toPlainText()
        self.zone_list.append(activeZoneSet)

        #OS
        fileSystemType = self.textEdit_46.toPlainText()
        isRAID = self.textEdit_45.toPlainText()
        RAIDLevel = self.textEdit_48.toPlainText()
        partitioningSchema = self.textEdit_47.toPlainText()
        OperatingSystemType = self.textEdit_22.toPlainText()
        packages = self.textEdit_49.toPlainText()
        packageManager = self.textEdit_53.toPlainText()
        installedPackages = self.textEdit_52.toPlainText()
        uninstalledPackages = self.textEdit_51.toPlainText()

        #Cloud 
        cloudTechnologyApplication = self.textEdit_54.toPlainText()
        neededPackages = self.textEdit_55.toPlainText()
        DataStoreFileSysyem = self.textEdit_56.toPlainText()
        databaseTool = self.textEdit_57.toPlainText()
        databaseAdminCredentials = self.textEdit_58.toPlainText()

        #systemt Network
        IPVersion_sys = self.textEdit_59.toPlainText()
        physicalDataNetworkIPRange_Sys = self.textEdit_60.toPlainText()
        numberOfVLANs = self.textEdit_61.toPlainText()
        topology = self.textEdit_62.toPlainText()
         


        dictionary = {'numberofServers': numberOfServers, 
                        'dictionaryOfServerNamesAndMACAddresses': dictionaryOfServerNamesAndMACAddresses, 
                        'numberOfHarddiskArrays': numberOfHarddiskArrays, 
                        'numberOfHarddisksInArray': numberOfHarddisksInArray,
                        'IPVersion': IPVersion,
                        'managementNetworkIPRange': managementNetworkIPRange,
                        'physicalDataNetworkIPRange': physicalDataNetworkIPRange,
                        'virtualMachineDataNetworkIPRange': virtualMachineDataNetworkIPRange,
                        'frontEndServerMACAddress': frontEndServerMACAddress, 
                        'frontEndServerIPAddress': frontEndServerIPAddress, 
                        'frontEndServerName': frontEndServerName,
                        'connectionServerName': connectionServerName, 
                        'connectionServerIPAddress': connectionServerIPAddress,
                        'connectionServerPortNumber': connectionServerPortNumber,
                        'storagePoolConfigurationPreferences': storagePoolConfigurationPreferences,

                        'numberOfHarddiskArrays_SAS': numberOfHarddiskArrays_SAS,  
                        'numberOfHarddisksInArray_SAS': numberOfHarddisksInArray_SAS, 
                        'numberOfServers_SAS': numberOfServers_SAS,
                        'serverNames_SAS': serverNames_SAS,
                        'basicKickstartConfigurations': basicKickstartConfigurations,
                        'hardiskToServerAssociationMatrix': hardiskToServerAssociationMatrix,
                        'activeZoneSet': self.zone_list[-1], 

                        'fileSystemType': fileSystemType, 
                        'isRAID': isRAID,
                        'RAIDLevel': RAIDLevel, 
                        'partitioningSchema': partitioningSchema, 
                        'OperatingSystemType': OperatingSystemType,
                        'packages': packages,
                        'packageManager': packageManager, 
                        'installedPackages': installedPackages,
                        'uninstalledPackages': uninstalledPackages, 

                        'cloudTechnologyApplication': cloudTechnologyApplication, 
                        'neededPackages': neededPackages, 
                        'DataStoreFileSysyem': DataStoreFileSysyem,
                        'databaseTool' : databaseTool,
                        'databaseAdminCredentials': databaseAdminCredentials,

                        'IPVersion_sys': IPVersion_sys,
                        'physicalDataNetworkIPRange_Sys': physicalDataNetworkIPRange_Sys,
                        'numberOfVLANs': numberOfVLANs,
                        'topology': topology
                        }


        json_object = json.dumps(dictionary, indent=4)
        with open("config.json", "w+") as outfile:
            outfile.write(json_object)



'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
'''