# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\curri\Last_Term\Graduation project\GUI_V2\UI_designs\front.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 651, 471))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.temp_button = QtWidgets.QRadioButton(self.centralwidget)
        self.temp_button.setGeometry(QtCore.QRect(30, 280, 271, 30))
        self.temp_button.setObjectName("temp_button")
        self.custm_button = QtWidgets.QRadioButton(self.centralwidget)
        self.custm_button.setGeometry(QtCore.QRect(30, 330, 171, 30))
        self.custm_button.setObjectName("custm_button")
        self.Next_button = QtWidgets.QPushButton(self.centralwidget)
        self.Next_button.setGeometry(QtCore.QRect(500, 390, 93, 28))
        self.Next_button.setObjectName("Next_button")
        self.actionDark_mode = QtWidgets.QAction(Dialog)
        self.actionDark_mode.setObjectName("actionDark_mode")
        self.actionLight_mode = QtWidgets.QAction(Dialog)
        self.actionLight_mode.setObjectName("actionLight_mode")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        Dialog.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        Dialog.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Main window</p></body></html>"))
        self.temp_button.setText(_translate("Dialog", "Choose from a Template "))
        self.custm_button.setText(_translate("Dialog", "Customize a Template"))
        self.Next_button.setText(_translate("Dialog", "Next"))
        self.actionDark_mode.setText(_translate("Dialog", "Dark mode"))
        self.actionLight_mode.setText(_translate("Dialog", "Light mode"))
import logo_rc
