# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\curri\Last_Term\Graduation project\GUI_V2\UI_designs\OS_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 480)
        self.Tipend = QtWidgets.QLineEdit(Form)
        self.Tipend.setGeometry(QtCore.QRect(210, 170, 221, 22))
        self.Tipend.setObjectName("Tipend")
        self.LinterfaceName = QtWidgets.QLabel(Form)
        self.LinterfaceName.setGeometry(QtCore.QRect(20, 250, 141, 16))
        self.LinterfaceName.setObjectName("LinterfaceName")
        self.Lnetmask = QtWidgets.QLabel(Form)
        self.Lnetmask.setGeometry(QtCore.QRect(20, 210, 141, 16))
        self.Lnetmask.setObjectName("Lnetmask")
        self.LIPend = QtWidgets.QLabel(Form)
        self.LIPend.setGeometry(QtCore.QRect(20, 170, 141, 16))
        self.LIPend.setObjectName("LIPend")
        self.combInterfacename = QtWidgets.QComboBox(Form)
        self.combInterfacename.setGeometry(QtCore.QRect(210, 250, 221, 22))
        self.combInterfacename.setObjectName("combInterfacename")
        self.combInterfacename.addItem("")
        self.combInterfacename.addItem("")
        self.combInterfacename.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 531, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Tipstart = QtWidgets.QLineEdit(Form)
        self.Tipstart.setGeometry(QtCore.QRect(210, 130, 221, 22))
        self.Tipstart.setObjectName("Tipstart")
        self.Tnetmask = QtWidgets.QLineEdit(Form)
        self.Tnetmask.setGeometry(QtCore.QRect(210, 210, 221, 22))
        self.Tnetmask.setObjectName("Tnetmask")
        self.dropOS = QtWidgets.QLabel(Form)
        self.dropOS.setGeometry(QtCore.QRect(20, 90, 151, 16))
        self.dropOS.setObjectName("dropOS")
        self.Add_button = QtWidgets.QPushButton(Form)
        self.Add_button.setGeometry(QtCore.QRect(350, 420, 93, 28))
        self.Add_button.setObjectName("Add_button")
        self.LIPstart = QtWidgets.QLabel(Form)
        self.LIPstart.setGeometry(QtCore.QRect(20, 130, 141, 16))
        self.LIPstart.setObjectName("LIPstart")
        self.combOS = QtWidgets.QComboBox(Form)
        self.combOS.setGeometry(QtCore.QRect(210, 90, 221, 22))
        self.combOS.setObjectName("combOS")
        self.combOS.addItem("")
        self.combOS.addItem("")
        self.combOS.addItem("")
        self.combOS.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LinterfaceName.setText(_translate("Form", "DHCP Interface Name"))
        self.Lnetmask.setText(_translate("Form", "DHCP range net mask"))
        self.LIPend.setText(_translate("Form", "DHCP range ip end"))
        self.combInterfacename.setItemText(0, _translate("Form", "Ethernet"))
        self.combInterfacename.setItemText(1, _translate("Form", "Wifi"))
        self.combInterfacename.setItemText(2, _translate("Form", "ISCSI"))
        self.label.setText(_translate("Form", "Choose OS to install"))
        self.dropOS.setText(_translate("Form", "Operating System Type"))
        self.Add_button.setText(_translate("Form", "Add"))
        self.LIPstart.setText(_translate("Form", "DHCP range ip start "))
        self.combOS.setItemText(0, _translate("Form", "Redhat"))
        self.combOS.setItemText(1, _translate("Form", "Centos"))
        self.combOS.setItemText(2, _translate("Form", "Sun Solaries"))
        self.combOS.setItemText(3, _translate("Form", "Vmware"))
