# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\curri\Last_Term\Graduation project\GUI_V2\UI_designs\Server.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.Lchoose = QtWidgets.QLabel(Dialog)
        self.Lchoose.setGeometry(QtCore.QRect(20, 20, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lchoose.setFont(font)
        self.Lchoose.setObjectName("Lchoose")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 70, 591, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 589, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chServer1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chServer1.setObjectName("chServer1")
        self.verticalLayout.addWidget(self.chServer1)
        self.chServer2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chServer2.setObjectName("chServer2")
        self.verticalLayout.addWidget(self.chServer2)
        self.chServer3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chServer3.setObjectName("chServer3")
        self.verticalLayout.addWidget(self.chServer3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Next_button = QtWidgets.QPushButton(Dialog)
        self.Next_button.setGeometry(QtCore.QRect(500, 390, 93, 28))
        self.Next_button.setObjectName("Next_button")
        self.Back_button = QtWidgets.QPushButton(Dialog)
        self.Back_button.setGeometry(QtCore.QRect(390, 390, 93, 28))
        self.Back_button.setObjectName("Back_button")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(40, 440, 401, 23))
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.progressBar.setProperty("value", 70)
        self.progressBar.setObjectName("progressBar")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(150, 260, 181, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Lchoose_2 = QtWidgets.QLabel(Dialog)
        self.Lchoose_2.setGeometry(QtCore.QRect(20, 250, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Lchoose_2.setFont(font)
        self.Lchoose_2.setObjectName("Lchoose_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(490, 260, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Lchoose.setText(_translate("Dialog", "Choose Server to install OS"))
        self.chServer1.setText(_translate("Dialog", "file 1"))
        self.chServer2.setText(_translate("Dialog", "file 2"))
        self.chServer3.setText(_translate("Dialog", "file 3"))
        self.Next_button.setText(_translate("Dialog", "Next"))
        self.Back_button.setText(_translate("Dialog", "Back"))
        self.comboBox.setItemText(0, _translate("Dialog", "Frontend"))
        self.comboBox.setItemText(1, _translate("Dialog", "Node"))
        self.Lchoose_2.setText(_translate("Dialog", "Choose Server Type"))
        self.pushButton.setText(_translate("Dialog", "Specify"))
