# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\curri\Last_Term\Graduation project\GUI_V2\UI_designs\show_partition.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(475, 480)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        widget.setFont(font)
        self.listView = QtWidgets.QListView(widget)
        self.listView.setGeometry(QtCore.QRect(20, 70, 431, 351))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(20, 30, 201, 16))
        self.label.setObjectName("label")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Partition"))
        self.label.setText(_translate("widget", "My Partition"))
