# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\curri\Last_Term\Graduation project\GUI_V2\UI_designs\Server_choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.Back_button = QtWidgets.QPushButton(Dialog)
        self.Back_button.setGeometry(QtCore.QRect(390, 390, 93, 28))
        self.Back_button.setObjectName("Back_button")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(20, 70, 591, 181))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 589, 179))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Lchoose = QtWidgets.QLabel(Dialog)
        self.Lchoose.setGeometry(QtCore.QRect(20, 20, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Lchoose.setFont(font)
        self.Lchoose.setObjectName("Lchoose")
        self.Next_button = QtWidgets.QPushButton(Dialog)
        self.Next_button.setGeometry(QtCore.QRect(500, 390, 93, 28))
        self.Next_button.setObjectName("Next_button")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(40, 440, 401, 23))
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.progressBar.setProperty("value", 80)
        self.progressBar.setObjectName("progressBar")
        self.Choose_button = QtWidgets.QPushButton(Dialog)
        self.Choose_button.setGeometry(QtCore.QRect(20, 260, 201, 41))
        self.Choose_button.setObjectName("Choose_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Back_button.setText(_translate("Dialog", "Back"))
        self.Lchoose.setText(_translate("Dialog", "Choose Server to install OS"))
        self.Next_button.setText(_translate("Dialog", "Next"))
        self.Choose_button.setText(_translate("Dialog", "Choose OS"))
